### Get all demands
GET http://localhost:3001/demand

### Find demand by id
GET http://localhost:3001/demand/2


### Create Demand
POST http://localhost:3001/demand
Content-Type: application/json

{
  "date": "2024-01-16T00:03:21.788Z",
  "totalPlan": "200",
  "description": "Descrição do produto"
}

### Update Demand
PATCH http://localhost:3001/demand/5
Content-Type: application/json

{
  "description": "description description description description description description description description description description description description ",
  "date": "2024-01-16T00:03:21.788Z",
  "totalPlan": "201",
  "status": "completed"
}

### Delete Demand
DELETE http://localhost:3001/demand/1